In [9]:
import requests
import xml.etree.ElementTree as ET
import pandas as pd

In [10]:
ns = '{http://www.volby.cz/prezident/}'

In [11]:
data = pd.DataFrame()
for i in range(1, 34):
    r = requests.get('http://80.188.53.60/pls/prezmedia/vysledky_okrsky?kolo=2&davka=' + str(i))
    root = ET.fromstring(r.text)
    for okr in root.findall(ns + 'OKRSEK'):
        tmp = okr.attrib
        tmp.update(okr.find(ns + 'UCAST_OKRSEK').attrib)
        for kand in okr.findall(ns + 'HLASY_OKRSEK'):
            tmp.update({'HLASY_0' + kand.get('PORADOVE_CISLO'): int(kand.get('HLASY'))})
        data = data.append(tmp, ignore_index=True)

In [12]:
data.columns

Index(['CIS_OBEC', 'CIS_OKRSEK', 'DATUM_CAS_ZPRAC', 'HLASY_07', 'HLASY_09',
       'ODEVZDANE_OBALKY', 'OPAKOVANE', 'PLATNE_HLASY', 'PORADI_ZPRAC',
       'VYDANE_OBALKY', 'ZAPSANI_VOLICI'],
      dtype='object')

In [13]:
data.rename(columns={
    'CIS_OBEC': 'OBEC', 
    'CIS_OKRSEK': 'OKRSEK', 
    'ODEVZDANE_OBALKY': 'ODEVZ_OBAL',
    'PLATNE_HLASY': 'PL_HL_CELK', 
    'VYDANE_OBALKY': 'VYD_OBALKY',
    'ZAPSANI_VOLICI': 'VOL_SEZNAM'
}, inplace=True)

In [14]:
data.fillna(0, inplace=True)

In [15]:
for col in data.columns:
    if col.startswith('HLASY_'):
        data[col] = data[col].astype('int')

In [16]:
data

,OBEC,OKRSEK,DATUM_CAS_ZPRAC,HLASY_07,HLASY_09,ODEVZ_OBAL,OPAKOVANE,PL_HL_CELK,PORADI_ZPRAC,VYD_OBALKY,VOL_SEZNAM
0,541281,5,2018-01-27T14:16:05,38,16,54,0,54,2,54,123
1,549584,2,2018-01-27T14:16:15,24,34,58,0,58,3,58,79
2,547701,1,2018-01-27T14:16:19,19,28,47,0,47,4,47,68
3,587206,1,2018-01-27T14:16:31,24,23,47,0,47,5,47,66
4,573060,5,2018-01-27T14:16:33,46,31,77,0,77,6,77,123
5,575500,8,2018-01-27T14:16:37,29,11,40,0,40,7,40,64
6,563960,3,2018-01-27T14:16:37,23,22,45,0,45,8,45,82
7,597678,6,2018-01-27T14:16:38,25,5,30,0,30,9,30,35
8,572667,1,2018-01-27T14:16:48,74,51,125,0,125,10,125,171
9,572241,11,2018-01-27T14:17:00,32,3,35,0,35,11,35,44
10,560448,1,2018-01-27T14:17:18,60,54,114,0,114,12,114,150
11,580783,1,2018-01-27T14:17:21,27,16,43,0,43,13,43,61
12,577731,18,2018-01-27T14:17:23,26,32,58,0,58,14,58,585
13,587214,1,2018-01-27T14:17:30,10,34,44,0,44,15,44,56
14,554294,4,2018-01-27T14:17:38,32,23,55,0,55,16,55,67
15,548383,2,2018-01-27T14:17:41,20,17,37,0,37,17,37,51
16,559806,3,2018-01-27T14:17:43,18,14,32,0,32,18,32,34
17,578312,1,2018-01-27T14:17:47,45,25,70,0,70,19,70,92
18,532878,1,2018-01-27T14:17:54,16,15,31,0,31,20,31,44
19,533271,7,2018-01-27T14:17:59,25,23,48,0,48,21,48,75
20,553573,1,2018-01-27T14:18:00,44,28,72,0,72,22,72,153
21,597783,9,2018-01-27T14:18:03,49,19,68,0,68,23,68,110
22,569208,1,2018-01-27T14:18:09,45,54,99,0,99,24,99,143
23,556254,7,2018-01-27T14:18:16,36,12,49,0,48,25,49,78
24,545911,8039,2018-01-27T14:18:19,22,17,39,0,39,26,39,107
25,549118,1,2018-01-27T14:18:20,17,17,34,0,34,27,34,40
26,555380,10,2018-01-27T14:18:29,34,19,53,0,53,28,53,103
27,568414,7,2018-01-27T14:18:30,82,58,140,0,140,29,140,194
28,541095,1,2018-01-27T14:18:31,53,29,82,0,82,30,82,102
29,561754,1,2018-01-27T14:18:33,13,19,33,0,32,31,33,45
...,...,...,...,...,...,...,...,...,...,...,...
14846,540226,1,2018-01-27T16:31:46,444,425,870,0,869,14848,870,1252
14847,537721,1,2018-01-27T16:32:11,275,365,641,0,640,14849,644,904
14848,500119,4035,2018-01-27T16:32:13,93,254,348,0,347,14850,348,479
14849,535320,1,2018-01-27T16:32:15,385,331,719,0,716,14851,719,1211
14850,500178,6046,2018-01-27T16:32:48,121,464,588,0,585,14852,588,726
14851,538230,1,2018-01-27T16:33:00,482,765,1248,0,1247,14853,1248,1618
14852,586528,1,2018-01-27T16:33:19,473,293,766,0,766,14854,766,1208
14853,529451,9,2018-01-27T16:33:42,119,93,212,0,212,14855,212,344
14854,500119,4123,2018-01-27T16:36:11,184,303,487,0,487,14856,488,700
14855,540226,2,2018-01-27T16:36:26,195,148,343,0,343,14857,344,411
14856,999997,39,2018-01-27T16:36:51,119,2141,2260,0,2260,14858,2260,2616
14857,538574,2,2018-01-27T16:37:03,428,734,1167,0,1162,14859,1168,1764
14858,500054,1008,2018-01-27T16:37:44,150,471,621,0,621,14860,621,910
14859,999997,14,2018-01-27T16:39:14,89,1154,1245,0,1243,14861,1245,1320
14860,500119,4124,2018-01-27T16:39:14,132,281,413,0,413,14862,413,616
14861,500224,10015,2018-01-27T16:39:42,264,692,957,0,956,14863,957,1280
14862,999997,56,2018-01-27T16:40:03,18,22,40,0,40,14864,40,40
14863,547051,38001,2018-01-27T16:42:45,267,555,829,0,822,14865,831,1215
14864,570451,2,2018-01-27T16:42:50,363,322,688,0,685,14866,688,1028
14865,500216,9036,2018-01-27T16:43:53,204,375,579,0,579,14867,579,833
14866,539210,1,2018-01-27T16:45:31,379,1242,1622,0,1621,14868,1622,2095
14867,500097,3026,2018-01-27T16:46:18,175,504,681,0,679,14869,681,999
14868,500097,3007,2018-01-27T16:47:29,125,446,574,0,571,14870,574,872
14869,556904,53,2018-01-27T16:47:35,426,467,893,0,893,14871,899,1537
14870,533955,7,2018-01-27T16:48:41,452,549,1008,0,1001,14872,1009,1274
14871,579742,1,2018-01-27T16:50:25,353,1552,1907,0,1905,14873,1907,2183
14872,576247,1,2018-01-27T16:50:40,200,602,803,0,802,14874,803,945
14873,500186,7009,2018-01-27T16:54:35,237,497,737,0,734,14875,737,1034
14874,538523,1,2018-01-27T16:55:51,471,849,1323,0,1320,14876,1323,1809
14875,579581,1,2018-01-27T16:58:55,163,1212,1377,0,1375,14877,1378,1466

In [17]:
data.to_csv('../scratch/okrsky_temp.csv', encoding='utf-8', index=False)